import sanitizeHtml from 'sanitize-html';

// Article body is rich HTML, authored by a `member` (or generated by the AI wizard from a
// member's brief) — both untrusted sources — so it's sanitised before it's ever stored or shown
// back to a client, per root CLAUDE.md's non-negotiable "Article HTML: always sanitise with
// sanitize-html before storing". Allowlist matches exactly what the write flow's Tiptap editor
// (apps/frontend/components/articles/RichTextEditor.tsx) can produce and the detail page
// renders — nothing more (no images/tables/scripts/styles). `h2`/`h3` predate that editor (which
// deliberately has no heading button, to avoid fighting the detail page's own heading hierarchy)
// and are effectively unused today, kept for backward compatibility rather than actively
// exercised. Shared by ArticlesService (member-authored save path) and AiService (AI-generated
// draft/refine responses) so there's exactly one allowlist to keep in sync with the editor.
export const ARTICLE_BODY_SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: ['p', 'h2', 'h3', 'ul', 'ol', 'li', 'blockquote', 'strong', 'em', 'u', 'code', 'pre', 'a', 'br'],
  allowedAttributes: { a: ['href', 'target', 'rel'] },
  allowedSchemes: ['https'],
};

export function sanitizeArticleBody(html: string): string {
  return sanitizeHtml(html, ARTICLE_BODY_SANITIZE_OPTIONS).trim();
}
